[build]
publish = "exampleSite/public"
command = """hugo \
  --source exampleSite \
  --config exampleSite/config.toml \
  --themesDir ../.. \
  --theme repo \
  --baseURL https://hugo-hero.netlify.com/"""

[context.deploy-preview.environment]
  HUGO_VERSION = "0.51"

[context.production.environment]
HUGO_VERSION = "0.51"